-- Add substitution fields to match_events to persist substitutions as first-class events
-- Generated by Cascade

begin;

alter table public.match_events
  add column if not exists sub_out_player_id uuid,
  add column if not exists sub_in_player_id uuid;

-- Optional: add foreign keys if you want enforced integrity (commented out if players table is large or you prefer loose coupling)
-- alter table public.match_events
--   add constraint match_events_sub_out_player_fk foreign key (sub_out_player_id) references public.players(id) on delete set null,
--   add constraint match_events_sub_in_player_fk  foreign key (sub_in_player_id)  references public.players(id) on delete set null;

-- Optional: partial index to speed up substitution queries
create index if not exists match_events_substitution_idx
  on public.match_events (fixture_id, period_id, total_match_minute)
  where event_type = 'substitution';

commit;
