-- Idempotent event writes: add client_event_id and unique constraint
-- Generated by Cascade

begin;

alter table public.match_events
add column if not exists client_event_id uuid;

create unique index if not exists match_events_client_event_id_key
on public.match_events(client_event_id)
where client_event_id is not null;

commit;
