-- Add missing columns to match_events used by the app: period_id, minute_in_period, total_match_minute
-- Generated by Cascade

begin;

alter table public.match_events
  add column if not exists period_id uuid,
  add column if not exists minute_in_period integer,
  add column if not exists total_match_minute integer;

-- Optional FKs (commented out):
-- alter table public.match_events
--   add constraint match_events_period_fk foreign key (period_id) references public.match_periods(id) on delete set null;

commit;
