-- Ensure enum event_type includes 'substitution' before creating indexes or inserting events
-- Generated by Cascade

begin;

-- Add enum value if it does not exist (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_enum e ON t.oid = e.enumtypid
    WHERE t.typname = 'event_type' AND e.enumlabel = 'substitution'
  ) THEN
    ALTER TYPE public.event_type ADD VALUE 'substitution';
  END IF;
END
$$;

commit;
